# Generated by Django 3.1 on 2024-02-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20240222_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
